# model
model:              "SMIN"          # Model name
checkpoint_path:    "checkpoints/"  # Model checkpoint path
resume_training:    False           # Resume training from previous checkpoint
T:                  128             # Number of frames to sample
L:                  32              # L x L moments out of T frames
C:                  4               # divide frame features in a moment into C parts
d:                  512             # Feature dimensions
input_video_dim:    4096            # C3D features dimension
dl:                 128             # Feature dimensions for Content-word interactions
max_query_length:   14              # Max length of the query
lstm_hidden_size:   256             # lstm hidden size
num_smi_layers:     3               # Number of Structured Multi-Level Interactions

# data
dataset:            "tacos"         # Dataset name
data_dir:           "data/tacos"    # Data directory
batch_size:         64              # Batch Size
num_workers:        4               # Number of workers for data loader

# training
seed:               43              # Random seed
optimizer:          "Adam"          # Optimizer type
lr:                 0.0005          # Learning rate
num_epochs:         100             # Number of epochs
